name: Event Graphics
favicon: null
layout_spectrum: 0.5505733645986766
typography_spectrum: 0.5605047645512968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.19007874792441726
  lightness: 0.4650207068771124
  saturation: 0.20990280574187636
  rhythmicContrast: 0.6305800001136959
purpose: []
