name: Event Graphics
favicon: null
layout_spectrum: 0.28309
typography_spectrum: 0.5605047645512968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefed8'
    - '#b2ae7e'
    - '#171812'
    - '#818574'
    - '#453b20'
  brandStrength: 0.5
  lightness: 0.4650207068771124
  saturation: 0.20990280574187636
  rhythmicContrast: 0.6305800001136959
purpose: []
